package Sendme::View::HTML;
use Moose;
use namespace::autoclean;

extends 'Catalyst::View::TT';

__PACKAGE__->config(
    TEMPLATE_EXTENSION => '.tt',
    render_die => 1,

    INCLUDE_PATH => [
        Sendme->path_to( 'templates', 'webapp' ),
    ],
);

=head1 NAME

Sendme::View::HTML - TT View for Sendme

=head1 DESCRIPTION

TT View for Sendme.

=head1 SEE ALSO

L<Sendme>

=head1 AUTHOR

=head2 Generated by

script/sendme_create.pl View HTML TT

=head2 Modified by

Simon Amor <simon@leaky.org>

=head1 LICENSE

This library is free software. You can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
